ALTER TABLE `interview_session` ADD `opened_at` integer;--> statement-breakpoint
CREATE INDEX `interview_session_application_idx` ON `interview_session` (`application_id`);--> statement-breakpoint
CREATE INDEX `interview_session_interview_idx` ON `interview_session` (`interview_id`);--> statement-breakpoint
CREATE INDEX `interview_session_bundle_idx` ON `interview_session` (`bundle_id`);--> statement-breakpoint
CREATE INDEX `application_status_idx` ON `application` (`status`);--> statement-breakpoint
CREATE INDEX `application_position_idx` ON `application` (`position_id`);--> statement-breakpoint
CREATE INDEX `application_created_idx` ON `application` (`created_at`);--> statement-breakpoint
CREATE INDEX `application_candidate_updated_idx` ON `application` (`candidate_id`,`updated_at`);--> statement-breakpoint
CREATE INDEX `audit_log_user_idx` ON `audit_log` (`user_id`);--> statement-breakpoint
CREATE INDEX `audit_log_entity_idx` ON `audit_log` (`entity_type`);--> statement-breakpoint
CREATE INDEX `audit_log_created_idx` ON `audit_log` (`created_at`);--> statement-breakpoint
CREATE INDEX `candidate_created_idx` ON `candidate` (`created_at`);--> statement-breakpoint
CREATE INDEX `candidate_source_idx` ON `candidate` (`source`);--> statement-breakpoint
CREATE INDEX `cas_candidate_created_idx` ON `candidate_ai_screening` (`candidate_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `cas_position_idx` ON `candidate_ai_screening` (`position_id`);--> statement-breakpoint
CREATE INDEX `candidate_document_candidate_idx` ON `candidate_document` (`candidate_id`);--> statement-breakpoint
CREATE INDEX `dcr_document_idx` ON `document_category_relations` (`document_id`);--> statement-breakpoint
CREATE INDEX `documents_created_idx` ON `documents` (`created_at`);--> statement-breakpoint
CREATE INDEX `employee_position_idx` ON `employee` (`position_id`);--> statement-breakpoint
CREATE INDEX `interview_application_idx` ON `interview` (`application_id`);--> statement-breakpoint
CREATE INDEX `interview_status_idx` ON `interview` (`status`);--> statement-breakpoint
CREATE INDEX `interview_scheduled_idx` ON `interview` (`scheduled_at`);--> statement-breakpoint
CREATE INDEX `interview_created_idx` ON `interview` (`created_at`);--> statement-breakpoint
CREATE INDEX `interview_rating_idx` ON `interview` (`rating`) WHERE "interview"."rating" is not null;--> statement-breakpoint
CREATE INDEX `iaa_interview_idx` ON `interview_ai_analysis` (`interview_id`);--> statement-breakpoint
CREATE INDEX `iaa_bundle_idx` ON `interview_ai_analysis` (`bundle_id`);--> statement-breakpoint
CREATE INDEX `interview_bundle_application_idx` ON `interview_bundle` (`application_id`);--> statement-breakpoint
CREATE INDEX `interview_bundle_round_session_idx` ON `interview_bundle_round` (`session_id`);--> statement-breakpoint
CREATE INDEX `question_bank_active_idx` ON `question_bank` (`is_active`);--> statement-breakpoint
CREATE INDEX `rwc_user_idx` ON `recruiter_weekly_checkin` (`user_id`);--> statement-breakpoint
CREATE INDEX `rwc_created_idx` ON `recruiter_weekly_checkin` (`created_at`);--> statement-breakpoint
CREATE INDEX `round_template_position_idx` ON `round_template` (`position_id`);--> statement-breakpoint
CREATE INDEX `rtq_round_idx` ON `round_template_questions` (`round_template_id`);--> statement-breakpoint
CREATE INDEX `rtq_question_idx` ON `round_template_questions` (`question_id`);