/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiInterviewSessionsRouteImport } from './routes/api/interview-sessions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainDocsRouteRouteImport } from './routes/_main/docs/route'
import { Route as MainAdminRouteRouteImport } from './routes/_main/admin/route'
import { Route as InterviewTokenIndexRouteImport } from './routes/interview/$token/index'
import { Route as ApiCandidateIndexRouteImport } from './routes/api/candidate/index'
import { Route as MainWeeklyCheckinIndexRouteImport } from './routes/_main/weekly-checkin/index'
import { Route as MainRoundsIndexRouteImport } from './routes/_main/rounds/index'
import { Route as MainQuestionsIndexRouteImport } from './routes/_main/questions/index'
import { Route as MainProfileIndexRouteImport } from './routes/_main/profile/index'
import { Route as MainPositionsIndexRouteImport } from './routes/_main/positions/index'
import { Route as MainInterviewsIndexRouteImport } from './routes/_main/interviews/index'
import { Route as MainEmployeesIndexRouteImport } from './routes/_main/employees/index'
import { Route as MainDocumentsIndexRouteImport } from './routes/_main/documents/index'
import { Route as MainDocsIndexRouteImport } from './routes/_main/docs/index'
import { Route as MainCandidatesIndexRouteImport } from './routes/_main/candidates/index'
import { Route as MainApplicationsIndexRouteImport } from './routes/_main/applications/index'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin/index'
import { Route as ApiLoginGoogleRouteImport } from './routes/api/login/google'
import { Route as ApiDocumentsViewRouteImport } from './routes/api/documents/view'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'
import { Route as ApiCandidateBulkRouteImport } from './routes/api/candidate/bulk'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuditLogsGenerateReportRouteImport } from './routes/api/audit-logs/generate-report'
import { Route as MainWeeklyCheckinRecordsRouteImport } from './routes/_main/weekly-checkin/records'
import { Route as MainRoundsNewRouteImport } from './routes/_main/rounds/new'
import { Route as MainQuestionsNewRouteImport } from './routes/_main/questions/new'
import { Route as MainProfileUserIdRouteImport } from './routes/_main/profile/$userId'
import { Route as MainPositionsNewRouteImport } from './routes/_main/positions/new'
import { Route as MainEmployeesNewRouteImport } from './routes/_main/employees/new'
import { Route as MainDocumentsNewRouteImport } from './routes/_main/documents/new'
import { Route as MainDocsWhatsNewRouteImport } from './routes/_main/docs/whats-new'
import { Route as MainDocsRoundsRouteImport } from './routes/_main/docs/rounds'
import { Route as MainDocsQuestionsRouteImport } from './routes/_main/docs/questions'
import { Route as MainDocsPositionsRouteImport } from './routes/_main/docs/positions'
import { Route as MainDocsInterviewsRouteImport } from './routes/_main/docs/interviews'
import { Route as MainDocsEmployeesRouteImport } from './routes/_main/docs/employees'
import { Route as MainDocsDocumentsRouteImport } from './routes/_main/docs/documents'
import { Route as MainDocsCandidatesRouteImport } from './routes/_main/docs/candidates'
import { Route as MainDocsApplicationsRouteImport } from './routes/_main/docs/applications'
import { Route as MainDocsAiFeaturesRouteImport } from './routes/_main/docs/ai-features'
import { Route as MainCandidatesNewRouteImport } from './routes/_main/candidates/new'
import { Route as MainAdminAuditLogsRouteImport } from './routes/_main/admin/audit-logs'
import { Route as ApiCandidateIdIndexRouteImport } from './routes/api/candidate/$id/index'
import { Route as MainRoundsIdIndexRouteImport } from './routes/_main/rounds/$id/index'
import { Route as MainQuestionsIdIndexRouteImport } from './routes/_main/questions/$id/index'
import { Route as MainPositionsSlugIndexRouteImport } from './routes/_main/positions/$slug/index'
import { Route as MainInterviewsIdIndexRouteImport } from './routes/_main/interviews/$id/index'
import { Route as MainEmployeesIdIndexRouteImport } from './routes/_main/employees/$id/index'
import { Route as MainCandidatesUidIndexRouteImport } from './routes/_main/candidates/$uid/index'
import { Route as MainApplicationsIdIndexRouteImport } from './routes/_main/applications/$id/index'
import { Route as ApiInterviewIdAiAnalysisRouteImport } from './routes/api/interview/$id/ai-analysis'
import { Route as ApiInterviewTokenTokenValidateRouteImport } from './routes/api/interview-token/$token/validate'
import { Route as ApiInterviewTokenTokenSchemaRouteImport } from './routes/api/interview-token/$token/schema'
import { Route as ApiInterviewTokenTokenResponsesRouteImport } from './routes/api/interview-token/$token/responses'
import { Route as ApiInterviewTokenTokenCompleteRouteImport } from './routes/api/interview-token/$token/complete'
import { Route as ApiCandidateIdDocumentsRouteImport } from './routes/api/candidate/$id/documents'
import { Route as ApiCandidateIdAiScreeningRouteImport } from './routes/api/candidate/$id/ai-screening'
import { Route as ApiCandidateIdAiAnalysisRouteImport } from './routes/api/candidate/$id/ai-analysis'
import { Route as MainRoundsIdEditRouteImport } from './routes/_main/rounds/$id/edit'
import { Route as MainRoundsIdAddQuestionRouteImport } from './routes/_main/rounds/$id/add-question'
import { Route as MainQuestionsIdEditRouteImport } from './routes/_main/questions/$id/edit'
import { Route as MainPositionsSlugEditRouteImport } from './routes/_main/positions/$slug/edit'
import { Route as MainEmployeesIdEditRouteImport } from './routes/_main/employees/$id/edit'
import { Route as MainCandidatesUidEditRouteImport } from './routes/_main/candidates/$uid/edit'
import { Route as ApiCandidateIdDocumentsDocumentIdRouteImport } from './routes/api/candidate/$id/documents/$documentId'
import { Route as MainCandidatesUidDocumentsDocumentIdEditRouteImport } from './routes/_main/candidates/$uid/documents/$documentId/edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiInterviewSessionsRoute = ApiInterviewSessionsRouteImport.update({
  id: '/api/interview-sessions',
  path: '/api/interview-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDocsRouteRoute = MainDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminRouteRoute = MainAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MainRouteRoute,
} as any)
const InterviewTokenIndexRoute = InterviewTokenIndexRouteImport.update({
  id: '/interview/$token/',
  path: '/interview/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidateIndexRoute = ApiCandidateIndexRouteImport.update({
  id: '/api/candidate/',
  path: '/api/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainWeeklyCheckinIndexRoute = MainWeeklyCheckinIndexRouteImport.update({
  id: '/weekly-checkin/',
  path: '/weekly-checkin/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRoundsIndexRoute = MainRoundsIndexRouteImport.update({
  id: '/rounds/',
  path: '/rounds/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainQuestionsIndexRoute = MainQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPositionsIndexRoute = MainPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainInterviewsIndexRoute = MainInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEmployeesIndexRoute = MainEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDocumentsIndexRoute = MainDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDocsIndexRoute = MainDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainCandidatesIndexRoute = MainCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainApplicationsIndexRoute = MainApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAdminRouteRoute,
} as any)
const ApiLoginGoogleRoute = ApiLoginGoogleRouteImport.update({
  id: '/api/login/google',
  path: '/api/login/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsViewRoute = ApiDocumentsViewRouteImport.update({
  id: '/api/documents/view',
  path: '/api/documents/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidateBulkRoute = ApiCandidateBulkRouteImport.update({
  id: '/api/candidate/bulk',
  path: '/api/candidate/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsGenerateReportRoute =
  ApiAuditLogsGenerateReportRouteImport.update({
    id: '/api/audit-logs/generate-report',
    path: '/api/audit-logs/generate-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainWeeklyCheckinRecordsRoute =
  MainWeeklyCheckinRecordsRouteImport.update({
    id: '/weekly-checkin/records',
    path: '/weekly-checkin/records',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainRoundsNewRoute = MainRoundsNewRouteImport.update({
  id: '/rounds/new',
  path: '/rounds/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainQuestionsNewRoute = MainQuestionsNewRouteImport.update({
  id: '/questions/new',
  path: '/questions/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileUserIdRoute = MainProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPositionsNewRoute = MainPositionsNewRouteImport.update({
  id: '/positions/new',
  path: '/positions/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEmployeesNewRoute = MainEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDocumentsNewRoute = MainDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDocsWhatsNewRoute = MainDocsWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsRoundsRoute = MainDocsRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsQuestionsRoute = MainDocsQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsPositionsRoute = MainDocsPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsInterviewsRoute = MainDocsInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsEmployeesRoute = MainDocsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsDocumentsRoute = MainDocsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsCandidatesRoute = MainDocsCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsApplicationsRoute = MainDocsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainDocsAiFeaturesRoute = MainDocsAiFeaturesRouteImport.update({
  id: '/ai-features',
  path: '/ai-features',
  getParentRoute: () => MainDocsRouteRoute,
} as any)
const MainCandidatesNewRoute = MainCandidatesNewRouteImport.update({
  id: '/candidates/new',
  path: '/candidates/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminAuditLogsRoute = MainAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => MainAdminRouteRoute,
} as any)
const ApiCandidateIdIndexRoute = ApiCandidateIdIndexRouteImport.update({
  id: '/api/candidate/$id/',
  path: '/api/candidate/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoundsIdIndexRoute = MainRoundsIdIndexRouteImport.update({
  id: '/rounds/$id/',
  path: '/rounds/$id/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainQuestionsIdIndexRoute = MainQuestionsIdIndexRouteImport.update({
  id: '/questions/$id/',
  path: '/questions/$id/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPositionsSlugIndexRoute = MainPositionsSlugIndexRouteImport.update({
  id: '/positions/$slug/',
  path: '/positions/$slug/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainInterviewsIdIndexRoute = MainInterviewsIdIndexRouteImport.update({
  id: '/interviews/$id/',
  path: '/interviews/$id/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEmployeesIdIndexRoute = MainEmployeesIdIndexRouteImport.update({
  id: '/employees/$id/',
  path: '/employees/$id/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCandidatesUidIndexRoute = MainCandidatesUidIndexRouteImport.update({
  id: '/candidates/$uid/',
  path: '/candidates/$uid/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainApplicationsIdIndexRoute = MainApplicationsIdIndexRouteImport.update({
  id: '/applications/$id/',
  path: '/applications/$id/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiInterviewIdAiAnalysisRoute =
  ApiInterviewIdAiAnalysisRouteImport.update({
    id: '/api/interview/$id/ai-analysis',
    path: '/api/interview/$id/ai-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInterviewTokenTokenValidateRoute =
  ApiInterviewTokenTokenValidateRouteImport.update({
    id: '/api/interview-token/$token/validate',
    path: '/api/interview-token/$token/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInterviewTokenTokenSchemaRoute =
  ApiInterviewTokenTokenSchemaRouteImport.update({
    id: '/api/interview-token/$token/schema',
    path: '/api/interview-token/$token/schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInterviewTokenTokenResponsesRoute =
  ApiInterviewTokenTokenResponsesRouteImport.update({
    id: '/api/interview-token/$token/responses',
    path: '/api/interview-token/$token/responses',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInterviewTokenTokenCompleteRoute =
  ApiInterviewTokenTokenCompleteRouteImport.update({
    id: '/api/interview-token/$token/complete',
    path: '/api/interview-token/$token/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCandidateIdDocumentsRoute = ApiCandidateIdDocumentsRouteImport.update({
  id: '/api/candidate/$id/documents',
  path: '/api/candidate/$id/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidateIdAiScreeningRoute =
  ApiCandidateIdAiScreeningRouteImport.update({
    id: '/api/candidate/$id/ai-screening',
    path: '/api/candidate/$id/ai-screening',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCandidateIdAiAnalysisRoute =
  ApiCandidateIdAiAnalysisRouteImport.update({
    id: '/api/candidate/$id/ai-analysis',
    path: '/api/candidate/$id/ai-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainRoundsIdEditRoute = MainRoundsIdEditRouteImport.update({
  id: '/rounds/$id/edit',
  path: '/rounds/$id/edit',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRoundsIdAddQuestionRoute = MainRoundsIdAddQuestionRouteImport.update({
  id: '/rounds/$id/add-question',
  path: '/rounds/$id/add-question',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainQuestionsIdEditRoute = MainQuestionsIdEditRouteImport.update({
  id: '/questions/$id/edit',
  path: '/questions/$id/edit',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPositionsSlugEditRoute = MainPositionsSlugEditRouteImport.update({
  id: '/positions/$slug/edit',
  path: '/positions/$slug/edit',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEmployeesIdEditRoute = MainEmployeesIdEditRouteImport.update({
  id: '/employees/$id/edit',
  path: '/employees/$id/edit',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCandidatesUidEditRoute = MainCandidatesUidEditRouteImport.update({
  id: '/candidates/$uid/edit',
  path: '/candidates/$uid/edit',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiCandidateIdDocumentsDocumentIdRoute =
  ApiCandidateIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ApiCandidateIdDocumentsRoute,
  } as any)
const MainCandidatesUidDocumentsDocumentIdEditRoute =
  MainCandidatesUidDocumentsDocumentIdEditRouteImport.update({
    id: '/candidates/$uid/documents/$documentId/edit',
    path: '/candidates/$uid/documents/$documentId/edit',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof MainAdminRouteRouteWithChildren
  '/docs': typeof MainDocsRouteRouteWithChildren
  '/dashboard': typeof MainDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/interview-sessions': typeof ApiInterviewSessionsRoute
  '/admin/audit-logs': typeof MainAdminAuditLogsRoute
  '/candidates/new': typeof MainCandidatesNewRoute
  '/docs/ai-features': typeof MainDocsAiFeaturesRoute
  '/docs/applications': typeof MainDocsApplicationsRoute
  '/docs/candidates': typeof MainDocsCandidatesRoute
  '/docs/documents': typeof MainDocsDocumentsRoute
  '/docs/employees': typeof MainDocsEmployeesRoute
  '/docs/interviews': typeof MainDocsInterviewsRoute
  '/docs/positions': typeof MainDocsPositionsRoute
  '/docs/questions': typeof MainDocsQuestionsRoute
  '/docs/rounds': typeof MainDocsRoundsRoute
  '/docs/whats-new': typeof MainDocsWhatsNewRoute
  '/documents/new': typeof MainDocumentsNewRoute
  '/employees/new': typeof MainEmployeesNewRoute
  '/positions/new': typeof MainPositionsNewRoute
  '/profile/$userId': typeof MainProfileUserIdRoute
  '/questions/new': typeof MainQuestionsNewRoute
  '/rounds/new': typeof MainRoundsNewRoute
  '/weekly-checkin/records': typeof MainWeeklyCheckinRecordsRoute
  '/api/audit-logs/generate-report': typeof ApiAuditLogsGenerateReportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/candidate/bulk': typeof ApiCandidateBulkRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/documents/view': typeof ApiDocumentsViewRoute
  '/api/login/google': typeof ApiLoginGoogleRoute
  '/admin/': typeof MainAdminIndexRoute
  '/applications/': typeof MainApplicationsIndexRoute
  '/candidates/': typeof MainCandidatesIndexRoute
  '/docs/': typeof MainDocsIndexRoute
  '/documents/': typeof MainDocumentsIndexRoute
  '/employees/': typeof MainEmployeesIndexRoute
  '/interviews/': typeof MainInterviewsIndexRoute
  '/positions/': typeof MainPositionsIndexRoute
  '/profile/': typeof MainProfileIndexRoute
  '/questions/': typeof MainQuestionsIndexRoute
  '/rounds/': typeof MainRoundsIndexRoute
  '/weekly-checkin/': typeof MainWeeklyCheckinIndexRoute
  '/api/candidate/': typeof ApiCandidateIndexRoute
  '/interview/$token/': typeof InterviewTokenIndexRoute
  '/candidates/$uid/edit': typeof MainCandidatesUidEditRoute
  '/employees/$id/edit': typeof MainEmployeesIdEditRoute
  '/positions/$slug/edit': typeof MainPositionsSlugEditRoute
  '/questions/$id/edit': typeof MainQuestionsIdEditRoute
  '/rounds/$id/add-question': typeof MainRoundsIdAddQuestionRoute
  '/rounds/$id/edit': typeof MainRoundsIdEditRoute
  '/api/candidate/$id/ai-analysis': typeof ApiCandidateIdAiAnalysisRoute
  '/api/candidate/$id/ai-screening': typeof ApiCandidateIdAiScreeningRoute
  '/api/candidate/$id/documents': typeof ApiCandidateIdDocumentsRouteWithChildren
  '/api/interview-token/$token/complete': typeof ApiInterviewTokenTokenCompleteRoute
  '/api/interview-token/$token/responses': typeof ApiInterviewTokenTokenResponsesRoute
  '/api/interview-token/$token/schema': typeof ApiInterviewTokenTokenSchemaRoute
  '/api/interview-token/$token/validate': typeof ApiInterviewTokenTokenValidateRoute
  '/api/interview/$id/ai-analysis': typeof ApiInterviewIdAiAnalysisRoute
  '/applications/$id/': typeof MainApplicationsIdIndexRoute
  '/candidates/$uid/': typeof MainCandidatesUidIndexRoute
  '/employees/$id/': typeof MainEmployeesIdIndexRoute
  '/interviews/$id/': typeof MainInterviewsIdIndexRoute
  '/positions/$slug/': typeof MainPositionsSlugIndexRoute
  '/questions/$id/': typeof MainQuestionsIdIndexRoute
  '/rounds/$id/': typeof MainRoundsIdIndexRoute
  '/api/candidate/$id/': typeof ApiCandidateIdIndexRoute
  '/api/candidate/$id/documents/$documentId': typeof ApiCandidateIdDocumentsDocumentIdRoute
  '/candidates/$uid/documents/$documentId/edit': typeof MainCandidatesUidDocumentsDocumentIdEditRoute
}
export interface FileRoutesByTo {
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof MainDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/interview-sessions': typeof ApiInterviewSessionsRoute
  '/': typeof MainIndexRoute
  '/admin/audit-logs': typeof MainAdminAuditLogsRoute
  '/candidates/new': typeof MainCandidatesNewRoute
  '/docs/ai-features': typeof MainDocsAiFeaturesRoute
  '/docs/applications': typeof MainDocsApplicationsRoute
  '/docs/candidates': typeof MainDocsCandidatesRoute
  '/docs/documents': typeof MainDocsDocumentsRoute
  '/docs/employees': typeof MainDocsEmployeesRoute
  '/docs/interviews': typeof MainDocsInterviewsRoute
  '/docs/positions': typeof MainDocsPositionsRoute
  '/docs/questions': typeof MainDocsQuestionsRoute
  '/docs/rounds': typeof MainDocsRoundsRoute
  '/docs/whats-new': typeof MainDocsWhatsNewRoute
  '/documents/new': typeof MainDocumentsNewRoute
  '/employees/new': typeof MainEmployeesNewRoute
  '/positions/new': typeof MainPositionsNewRoute
  '/profile/$userId': typeof MainProfileUserIdRoute
  '/questions/new': typeof MainQuestionsNewRoute
  '/rounds/new': typeof MainRoundsNewRoute
  '/weekly-checkin/records': typeof MainWeeklyCheckinRecordsRoute
  '/api/audit-logs/generate-report': typeof ApiAuditLogsGenerateReportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/candidate/bulk': typeof ApiCandidateBulkRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/documents/view': typeof ApiDocumentsViewRoute
  '/api/login/google': typeof ApiLoginGoogleRoute
  '/admin': typeof MainAdminIndexRoute
  '/applications': typeof MainApplicationsIndexRoute
  '/candidates': typeof MainCandidatesIndexRoute
  '/docs': typeof MainDocsIndexRoute
  '/documents': typeof MainDocumentsIndexRoute
  '/employees': typeof MainEmployeesIndexRoute
  '/interviews': typeof MainInterviewsIndexRoute
  '/positions': typeof MainPositionsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/questions': typeof MainQuestionsIndexRoute
  '/rounds': typeof MainRoundsIndexRoute
  '/weekly-checkin': typeof MainWeeklyCheckinIndexRoute
  '/api/candidate': typeof ApiCandidateIndexRoute
  '/interview/$token': typeof InterviewTokenIndexRoute
  '/candidates/$uid/edit': typeof MainCandidatesUidEditRoute
  '/employees/$id/edit': typeof MainEmployeesIdEditRoute
  '/positions/$slug/edit': typeof MainPositionsSlugEditRoute
  '/questions/$id/edit': typeof MainQuestionsIdEditRoute
  '/rounds/$id/add-question': typeof MainRoundsIdAddQuestionRoute
  '/rounds/$id/edit': typeof MainRoundsIdEditRoute
  '/api/candidate/$id/ai-analysis': typeof ApiCandidateIdAiAnalysisRoute
  '/api/candidate/$id/ai-screening': typeof ApiCandidateIdAiScreeningRoute
  '/api/candidate/$id/documents': typeof ApiCandidateIdDocumentsRouteWithChildren
  '/api/interview-token/$token/complete': typeof ApiInterviewTokenTokenCompleteRoute
  '/api/interview-token/$token/responses': typeof ApiInterviewTokenTokenResponsesRoute
  '/api/interview-token/$token/schema': typeof ApiInterviewTokenTokenSchemaRoute
  '/api/interview-token/$token/validate': typeof ApiInterviewTokenTokenValidateRoute
  '/api/interview/$id/ai-analysis': typeof ApiInterviewIdAiAnalysisRoute
  '/applications/$id': typeof MainApplicationsIdIndexRoute
  '/candidates/$uid': typeof MainCandidatesUidIndexRoute
  '/employees/$id': typeof MainEmployeesIdIndexRoute
  '/interviews/$id': typeof MainInterviewsIdIndexRoute
  '/positions/$slug': typeof MainPositionsSlugIndexRoute
  '/questions/$id': typeof MainQuestionsIdIndexRoute
  '/rounds/$id': typeof MainRoundsIdIndexRoute
  '/api/candidate/$id': typeof ApiCandidateIdIndexRoute
  '/api/candidate/$id/documents/$documentId': typeof ApiCandidateIdDocumentsDocumentIdRoute
  '/candidates/$uid/documents/$documentId/edit': typeof MainCandidatesUidDocumentsDocumentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_main/admin': typeof MainAdminRouteRouteWithChildren
  '/_main/docs': typeof MainDocsRouteRouteWithChildren
  '/_main/dashboard': typeof MainDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/interview-sessions': typeof ApiInterviewSessionsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/admin/audit-logs': typeof MainAdminAuditLogsRoute
  '/_main/candidates/new': typeof MainCandidatesNewRoute
  '/_main/docs/ai-features': typeof MainDocsAiFeaturesRoute
  '/_main/docs/applications': typeof MainDocsApplicationsRoute
  '/_main/docs/candidates': typeof MainDocsCandidatesRoute
  '/_main/docs/documents': typeof MainDocsDocumentsRoute
  '/_main/docs/employees': typeof MainDocsEmployeesRoute
  '/_main/docs/interviews': typeof MainDocsInterviewsRoute
  '/_main/docs/positions': typeof MainDocsPositionsRoute
  '/_main/docs/questions': typeof MainDocsQuestionsRoute
  '/_main/docs/rounds': typeof MainDocsRoundsRoute
  '/_main/docs/whats-new': typeof MainDocsWhatsNewRoute
  '/_main/documents/new': typeof MainDocumentsNewRoute
  '/_main/employees/new': typeof MainEmployeesNewRoute
  '/_main/positions/new': typeof MainPositionsNewRoute
  '/_main/profile/$userId': typeof MainProfileUserIdRoute
  '/_main/questions/new': typeof MainQuestionsNewRoute
  '/_main/rounds/new': typeof MainRoundsNewRoute
  '/_main/weekly-checkin/records': typeof MainWeeklyCheckinRecordsRoute
  '/api/audit-logs/generate-report': typeof ApiAuditLogsGenerateReportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/candidate/bulk': typeof ApiCandidateBulkRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/documents/view': typeof ApiDocumentsViewRoute
  '/api/login/google': typeof ApiLoginGoogleRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/applications/': typeof MainApplicationsIndexRoute
  '/_main/candidates/': typeof MainCandidatesIndexRoute
  '/_main/docs/': typeof MainDocsIndexRoute
  '/_main/documents/': typeof MainDocumentsIndexRoute
  '/_main/employees/': typeof MainEmployeesIndexRoute
  '/_main/interviews/': typeof MainInterviewsIndexRoute
  '/_main/positions/': typeof MainPositionsIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/questions/': typeof MainQuestionsIndexRoute
  '/_main/rounds/': typeof MainRoundsIndexRoute
  '/_main/weekly-checkin/': typeof MainWeeklyCheckinIndexRoute
  '/api/candidate/': typeof ApiCandidateIndexRoute
  '/interview/$token/': typeof InterviewTokenIndexRoute
  '/_main/candidates/$uid/edit': typeof MainCandidatesUidEditRoute
  '/_main/employees/$id/edit': typeof MainEmployeesIdEditRoute
  '/_main/positions/$slug/edit': typeof MainPositionsSlugEditRoute
  '/_main/questions/$id/edit': typeof MainQuestionsIdEditRoute
  '/_main/rounds/$id/add-question': typeof MainRoundsIdAddQuestionRoute
  '/_main/rounds/$id/edit': typeof MainRoundsIdEditRoute
  '/api/candidate/$id/ai-analysis': typeof ApiCandidateIdAiAnalysisRoute
  '/api/candidate/$id/ai-screening': typeof ApiCandidateIdAiScreeningRoute
  '/api/candidate/$id/documents': typeof ApiCandidateIdDocumentsRouteWithChildren
  '/api/interview-token/$token/complete': typeof ApiInterviewTokenTokenCompleteRoute
  '/api/interview-token/$token/responses': typeof ApiInterviewTokenTokenResponsesRoute
  '/api/interview-token/$token/schema': typeof ApiInterviewTokenTokenSchemaRoute
  '/api/interview-token/$token/validate': typeof ApiInterviewTokenTokenValidateRoute
  '/api/interview/$id/ai-analysis': typeof ApiInterviewIdAiAnalysisRoute
  '/_main/applications/$id/': typeof MainApplicationsIdIndexRoute
  '/_main/candidates/$uid/': typeof MainCandidatesUidIndexRoute
  '/_main/employees/$id/': typeof MainEmployeesIdIndexRoute
  '/_main/interviews/$id/': typeof MainInterviewsIdIndexRoute
  '/_main/positions/$slug/': typeof MainPositionsSlugIndexRoute
  '/_main/questions/$id/': typeof MainQuestionsIdIndexRoute
  '/_main/rounds/$id/': typeof MainRoundsIdIndexRoute
  '/api/candidate/$id/': typeof ApiCandidateIdIndexRoute
  '/api/candidate/$id/documents/$documentId': typeof ApiCandidateIdDocumentsDocumentIdRoute
  '/_main/candidates/$uid/documents/$documentId/edit': typeof MainCandidatesUidDocumentsDocumentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/admin'
    | '/docs'
    | '/dashboard'
    | '/api/health'
    | '/api/interview-sessions'
    | '/admin/audit-logs'
    | '/candidates/new'
    | '/docs/ai-features'
    | '/docs/applications'
    | '/docs/candidates'
    | '/docs/documents'
    | '/docs/employees'
    | '/docs/interviews'
    | '/docs/positions'
    | '/docs/questions'
    | '/docs/rounds'
    | '/docs/whats-new'
    | '/documents/new'
    | '/employees/new'
    | '/positions/new'
    | '/profile/$userId'
    | '/questions/new'
    | '/rounds/new'
    | '/weekly-checkin/records'
    | '/api/audit-logs/generate-report'
    | '/api/auth/$'
    | '/api/candidate/bulk'
    | '/api/documents/upload'
    | '/api/documents/view'
    | '/api/login/google'
    | '/admin/'
    | '/applications/'
    | '/candidates/'
    | '/docs/'
    | '/documents/'
    | '/employees/'
    | '/interviews/'
    | '/positions/'
    | '/profile/'
    | '/questions/'
    | '/rounds/'
    | '/weekly-checkin/'
    | '/api/candidate/'
    | '/interview/$token/'
    | '/candidates/$uid/edit'
    | '/employees/$id/edit'
    | '/positions/$slug/edit'
    | '/questions/$id/edit'
    | '/rounds/$id/add-question'
    | '/rounds/$id/edit'
    | '/api/candidate/$id/ai-analysis'
    | '/api/candidate/$id/ai-screening'
    | '/api/candidate/$id/documents'
    | '/api/interview-token/$token/complete'
    | '/api/interview-token/$token/responses'
    | '/api/interview-token/$token/schema'
    | '/api/interview-token/$token/validate'
    | '/api/interview/$id/ai-analysis'
    | '/applications/$id/'
    | '/candidates/$uid/'
    | '/employees/$id/'
    | '/interviews/$id/'
    | '/positions/$slug/'
    | '/questions/$id/'
    | '/rounds/$id/'
    | '/api/candidate/$id/'
    | '/api/candidate/$id/documents/$documentId'
    | '/candidates/$uid/documents/$documentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/customScript.js'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/api/health'
    | '/api/interview-sessions'
    | '/'
    | '/admin/audit-logs'
    | '/candidates/new'
    | '/docs/ai-features'
    | '/docs/applications'
    | '/docs/candidates'
    | '/docs/documents'
    | '/docs/employees'
    | '/docs/interviews'
    | '/docs/positions'
    | '/docs/questions'
    | '/docs/rounds'
    | '/docs/whats-new'
    | '/documents/new'
    | '/employees/new'
    | '/positions/new'
    | '/profile/$userId'
    | '/questions/new'
    | '/rounds/new'
    | '/weekly-checkin/records'
    | '/api/audit-logs/generate-report'
    | '/api/auth/$'
    | '/api/candidate/bulk'
    | '/api/documents/upload'
    | '/api/documents/view'
    | '/api/login/google'
    | '/admin'
    | '/applications'
    | '/candidates'
    | '/docs'
    | '/documents'
    | '/employees'
    | '/interviews'
    | '/positions'
    | '/profile'
    | '/questions'
    | '/rounds'
    | '/weekly-checkin'
    | '/api/candidate'
    | '/interview/$token'
    | '/candidates/$uid/edit'
    | '/employees/$id/edit'
    | '/positions/$slug/edit'
    | '/questions/$id/edit'
    | '/rounds/$id/add-question'
    | '/rounds/$id/edit'
    | '/api/candidate/$id/ai-analysis'
    | '/api/candidate/$id/ai-screening'
    | '/api/candidate/$id/documents'
    | '/api/interview-token/$token/complete'
    | '/api/interview-token/$token/responses'
    | '/api/interview-token/$token/schema'
    | '/api/interview-token/$token/validate'
    | '/api/interview/$id/ai-analysis'
    | '/applications/$id'
    | '/candidates/$uid'
    | '/employees/$id'
    | '/interviews/$id'
    | '/positions/$slug'
    | '/questions/$id'
    | '/rounds/$id'
    | '/api/candidate/$id'
    | '/api/candidate/$id/documents/$documentId'
    | '/candidates/$uid/documents/$documentId/edit'
  id:
    | '__root__'
    | '/_main'
    | '/customScript.js'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/_main/admin'
    | '/_main/docs'
    | '/_main/dashboard'
    | '/api/health'
    | '/api/interview-sessions'
    | '/_main/'
    | '/_main/admin/audit-logs'
    | '/_main/candidates/new'
    | '/_main/docs/ai-features'
    | '/_main/docs/applications'
    | '/_main/docs/candidates'
    | '/_main/docs/documents'
    | '/_main/docs/employees'
    | '/_main/docs/interviews'
    | '/_main/docs/positions'
    | '/_main/docs/questions'
    | '/_main/docs/rounds'
    | '/_main/docs/whats-new'
    | '/_main/documents/new'
    | '/_main/employees/new'
    | '/_main/positions/new'
    | '/_main/profile/$userId'
    | '/_main/questions/new'
    | '/_main/rounds/new'
    | '/_main/weekly-checkin/records'
    | '/api/audit-logs/generate-report'
    | '/api/auth/$'
    | '/api/candidate/bulk'
    | '/api/documents/upload'
    | '/api/documents/view'
    | '/api/login/google'
    | '/_main/admin/'
    | '/_main/applications/'
    | '/_main/candidates/'
    | '/_main/docs/'
    | '/_main/documents/'
    | '/_main/employees/'
    | '/_main/interviews/'
    | '/_main/positions/'
    | '/_main/profile/'
    | '/_main/questions/'
    | '/_main/rounds/'
    | '/_main/weekly-checkin/'
    | '/api/candidate/'
    | '/interview/$token/'
    | '/_main/candidates/$uid/edit'
    | '/_main/employees/$id/edit'
    | '/_main/positions/$slug/edit'
    | '/_main/questions/$id/edit'
    | '/_main/rounds/$id/add-question'
    | '/_main/rounds/$id/edit'
    | '/api/candidate/$id/ai-analysis'
    | '/api/candidate/$id/ai-screening'
    | '/api/candidate/$id/documents'
    | '/api/interview-token/$token/complete'
    | '/api/interview-token/$token/responses'
    | '/api/interview-token/$token/schema'
    | '/api/interview-token/$token/validate'
    | '/api/interview/$id/ai-analysis'
    | '/_main/applications/$id/'
    | '/_main/candidates/$uid/'
    | '/_main/employees/$id/'
    | '/_main/interviews/$id/'
    | '/_main/positions/$slug/'
    | '/_main/questions/$id/'
    | '/_main/rounds/$id/'
    | '/api/candidate/$id/'
    | '/api/candidate/$id/documents/$documentId'
    | '/_main/candidates/$uid/documents/$documentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInterviewSessionsRoute: typeof ApiInterviewSessionsRoute
  ApiAuditLogsGenerateReportRoute: typeof ApiAuditLogsGenerateReportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCandidateBulkRoute: typeof ApiCandidateBulkRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
  ApiDocumentsViewRoute: typeof ApiDocumentsViewRoute
  ApiLoginGoogleRoute: typeof ApiLoginGoogleRoute
  ApiCandidateIndexRoute: typeof ApiCandidateIndexRoute
  InterviewTokenIndexRoute: typeof InterviewTokenIndexRoute
  ApiCandidateIdAiAnalysisRoute: typeof ApiCandidateIdAiAnalysisRoute
  ApiCandidateIdAiScreeningRoute: typeof ApiCandidateIdAiScreeningRoute
  ApiCandidateIdDocumentsRoute: typeof ApiCandidateIdDocumentsRouteWithChildren
  ApiInterviewTokenTokenCompleteRoute: typeof ApiInterviewTokenTokenCompleteRoute
  ApiInterviewTokenTokenResponsesRoute: typeof ApiInterviewTokenTokenResponsesRoute
  ApiInterviewTokenTokenSchemaRoute: typeof ApiInterviewTokenTokenSchemaRoute
  ApiInterviewTokenTokenValidateRoute: typeof ApiInterviewTokenTokenValidateRoute
  ApiInterviewIdAiAnalysisRoute: typeof ApiInterviewIdAiAnalysisRoute
  ApiCandidateIdIndexRoute: typeof ApiCandidateIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/interview-sessions': {
      id: '/api/interview-sessions'
      path: '/api/interview-sessions'
      fullPath: '/api/interview-sessions'
      preLoaderRoute: typeof ApiInterviewSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/docs': {
      id: '/_main/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof MainDocsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin': {
      id: '/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainAdminRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/interview/$token/': {
      id: '/interview/$token/'
      path: '/interview/$token'
      fullPath: '/interview/$token/'
      preLoaderRoute: typeof InterviewTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidate/': {
      id: '/api/candidate/'
      path: '/api/candidate'
      fullPath: '/api/candidate/'
      preLoaderRoute: typeof ApiCandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/weekly-checkin/': {
      id: '/_main/weekly-checkin/'
      path: '/weekly-checkin'
      fullPath: '/weekly-checkin/'
      preLoaderRoute: typeof MainWeeklyCheckinIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/rounds/': {
      id: '/_main/rounds/'
      path: '/rounds'
      fullPath: '/rounds/'
      preLoaderRoute: typeof MainRoundsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/questions/': {
      id: '/_main/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof MainQuestionsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/positions/': {
      id: '/_main/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof MainPositionsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/interviews/': {
      id: '/_main/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof MainInterviewsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/employees/': {
      id: '/_main/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof MainEmployeesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/documents/': {
      id: '/_main/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof MainDocumentsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/docs/': {
      id: '/_main/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof MainDocsIndexRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/candidates/': {
      id: '/_main/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof MainCandidatesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/applications/': {
      id: '/_main/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof MainApplicationsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainAdminRouteRoute
    }
    '/api/login/google': {
      id: '/api/login/google'
      path: '/api/login/google'
      fullPath: '/api/login/google'
      preLoaderRoute: typeof ApiLoginGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/view': {
      id: '/api/documents/view'
      path: '/api/documents/view'
      fullPath: '/api/documents/view'
      preLoaderRoute: typeof ApiDocumentsViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidate/bulk': {
      id: '/api/candidate/bulk'
      path: '/api/candidate/bulk'
      fullPath: '/api/candidate/bulk'
      preLoaderRoute: typeof ApiCandidateBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs/generate-report': {
      id: '/api/audit-logs/generate-report'
      path: '/api/audit-logs/generate-report'
      fullPath: '/api/audit-logs/generate-report'
      preLoaderRoute: typeof ApiAuditLogsGenerateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/weekly-checkin/records': {
      id: '/_main/weekly-checkin/records'
      path: '/weekly-checkin/records'
      fullPath: '/weekly-checkin/records'
      preLoaderRoute: typeof MainWeeklyCheckinRecordsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/rounds/new': {
      id: '/_main/rounds/new'
      path: '/rounds/new'
      fullPath: '/rounds/new'
      preLoaderRoute: typeof MainRoundsNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/questions/new': {
      id: '/_main/questions/new'
      path: '/questions/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof MainQuestionsNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/$userId': {
      id: '/_main/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof MainProfileUserIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/positions/new': {
      id: '/_main/positions/new'
      path: '/positions/new'
      fullPath: '/positions/new'
      preLoaderRoute: typeof MainPositionsNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/employees/new': {
      id: '/_main/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof MainEmployeesNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/documents/new': {
      id: '/_main/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof MainDocumentsNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/docs/whats-new': {
      id: '/_main/docs/whats-new'
      path: '/whats-new'
      fullPath: '/docs/whats-new'
      preLoaderRoute: typeof MainDocsWhatsNewRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/rounds': {
      id: '/_main/docs/rounds'
      path: '/rounds'
      fullPath: '/docs/rounds'
      preLoaderRoute: typeof MainDocsRoundsRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/questions': {
      id: '/_main/docs/questions'
      path: '/questions'
      fullPath: '/docs/questions'
      preLoaderRoute: typeof MainDocsQuestionsRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/positions': {
      id: '/_main/docs/positions'
      path: '/positions'
      fullPath: '/docs/positions'
      preLoaderRoute: typeof MainDocsPositionsRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/interviews': {
      id: '/_main/docs/interviews'
      path: '/interviews'
      fullPath: '/docs/interviews'
      preLoaderRoute: typeof MainDocsInterviewsRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/employees': {
      id: '/_main/docs/employees'
      path: '/employees'
      fullPath: '/docs/employees'
      preLoaderRoute: typeof MainDocsEmployeesRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/documents': {
      id: '/_main/docs/documents'
      path: '/documents'
      fullPath: '/docs/documents'
      preLoaderRoute: typeof MainDocsDocumentsRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/candidates': {
      id: '/_main/docs/candidates'
      path: '/candidates'
      fullPath: '/docs/candidates'
      preLoaderRoute: typeof MainDocsCandidatesRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/applications': {
      id: '/_main/docs/applications'
      path: '/applications'
      fullPath: '/docs/applications'
      preLoaderRoute: typeof MainDocsApplicationsRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/docs/ai-features': {
      id: '/_main/docs/ai-features'
      path: '/ai-features'
      fullPath: '/docs/ai-features'
      preLoaderRoute: typeof MainDocsAiFeaturesRouteImport
      parentRoute: typeof MainDocsRouteRoute
    }
    '/_main/candidates/new': {
      id: '/_main/candidates/new'
      path: '/candidates/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof MainCandidatesNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/audit-logs': {
      id: '/_main/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof MainAdminAuditLogsRouteImport
      parentRoute: typeof MainAdminRouteRoute
    }
    '/api/candidate/$id/': {
      id: '/api/candidate/$id/'
      path: '/api/candidate/$id'
      fullPath: '/api/candidate/$id/'
      preLoaderRoute: typeof ApiCandidateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/rounds/$id/': {
      id: '/_main/rounds/$id/'
      path: '/rounds/$id'
      fullPath: '/rounds/$id/'
      preLoaderRoute: typeof MainRoundsIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/questions/$id/': {
      id: '/_main/questions/$id/'
      path: '/questions/$id'
      fullPath: '/questions/$id/'
      preLoaderRoute: typeof MainQuestionsIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/positions/$slug/': {
      id: '/_main/positions/$slug/'
      path: '/positions/$slug'
      fullPath: '/positions/$slug/'
      preLoaderRoute: typeof MainPositionsSlugIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/interviews/$id/': {
      id: '/_main/interviews/$id/'
      path: '/interviews/$id'
      fullPath: '/interviews/$id/'
      preLoaderRoute: typeof MainInterviewsIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/employees/$id/': {
      id: '/_main/employees/$id/'
      path: '/employees/$id'
      fullPath: '/employees/$id/'
      preLoaderRoute: typeof MainEmployeesIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/candidates/$uid/': {
      id: '/_main/candidates/$uid/'
      path: '/candidates/$uid'
      fullPath: '/candidates/$uid/'
      preLoaderRoute: typeof MainCandidatesUidIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/applications/$id/': {
      id: '/_main/applications/$id/'
      path: '/applications/$id'
      fullPath: '/applications/$id/'
      preLoaderRoute: typeof MainApplicationsIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/interview/$id/ai-analysis': {
      id: '/api/interview/$id/ai-analysis'
      path: '/api/interview/$id/ai-analysis'
      fullPath: '/api/interview/$id/ai-analysis'
      preLoaderRoute: typeof ApiInterviewIdAiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-token/$token/validate': {
      id: '/api/interview-token/$token/validate'
      path: '/api/interview-token/$token/validate'
      fullPath: '/api/interview-token/$token/validate'
      preLoaderRoute: typeof ApiInterviewTokenTokenValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-token/$token/schema': {
      id: '/api/interview-token/$token/schema'
      path: '/api/interview-token/$token/schema'
      fullPath: '/api/interview-token/$token/schema'
      preLoaderRoute: typeof ApiInterviewTokenTokenSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-token/$token/responses': {
      id: '/api/interview-token/$token/responses'
      path: '/api/interview-token/$token/responses'
      fullPath: '/api/interview-token/$token/responses'
      preLoaderRoute: typeof ApiInterviewTokenTokenResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-token/$token/complete': {
      id: '/api/interview-token/$token/complete'
      path: '/api/interview-token/$token/complete'
      fullPath: '/api/interview-token/$token/complete'
      preLoaderRoute: typeof ApiInterviewTokenTokenCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidate/$id/documents': {
      id: '/api/candidate/$id/documents'
      path: '/api/candidate/$id/documents'
      fullPath: '/api/candidate/$id/documents'
      preLoaderRoute: typeof ApiCandidateIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidate/$id/ai-screening': {
      id: '/api/candidate/$id/ai-screening'
      path: '/api/candidate/$id/ai-screening'
      fullPath: '/api/candidate/$id/ai-screening'
      preLoaderRoute: typeof ApiCandidateIdAiScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidate/$id/ai-analysis': {
      id: '/api/candidate/$id/ai-analysis'
      path: '/api/candidate/$id/ai-analysis'
      fullPath: '/api/candidate/$id/ai-analysis'
      preLoaderRoute: typeof ApiCandidateIdAiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/rounds/$id/edit': {
      id: '/_main/rounds/$id/edit'
      path: '/rounds/$id/edit'
      fullPath: '/rounds/$id/edit'
      preLoaderRoute: typeof MainRoundsIdEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/rounds/$id/add-question': {
      id: '/_main/rounds/$id/add-question'
      path: '/rounds/$id/add-question'
      fullPath: '/rounds/$id/add-question'
      preLoaderRoute: typeof MainRoundsIdAddQuestionRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/questions/$id/edit': {
      id: '/_main/questions/$id/edit'
      path: '/questions/$id/edit'
      fullPath: '/questions/$id/edit'
      preLoaderRoute: typeof MainQuestionsIdEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/positions/$slug/edit': {
      id: '/_main/positions/$slug/edit'
      path: '/positions/$slug/edit'
      fullPath: '/positions/$slug/edit'
      preLoaderRoute: typeof MainPositionsSlugEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/employees/$id/edit': {
      id: '/_main/employees/$id/edit'
      path: '/employees/$id/edit'
      fullPath: '/employees/$id/edit'
      preLoaderRoute: typeof MainEmployeesIdEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/candidates/$uid/edit': {
      id: '/_main/candidates/$uid/edit'
      path: '/candidates/$uid/edit'
      fullPath: '/candidates/$uid/edit'
      preLoaderRoute: typeof MainCandidatesUidEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/candidate/$id/documents/$documentId': {
      id: '/api/candidate/$id/documents/$documentId'
      path: '/$documentId'
      fullPath: '/api/candidate/$id/documents/$documentId'
      preLoaderRoute: typeof ApiCandidateIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ApiCandidateIdDocumentsRoute
    }
    '/_main/candidates/$uid/documents/$documentId/edit': {
      id: '/_main/candidates/$uid/documents/$documentId/edit'
      path: '/candidates/$uid/documents/$documentId/edit'
      fullPath: '/candidates/$uid/documents/$documentId/edit'
      preLoaderRoute: typeof MainCandidatesUidDocumentsDocumentIdEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainAdminRouteRouteChildren {
  MainAdminAuditLogsRoute: typeof MainAdminAuditLogsRoute
  MainAdminIndexRoute: typeof MainAdminIndexRoute
}

const MainAdminRouteRouteChildren: MainAdminRouteRouteChildren = {
  MainAdminAuditLogsRoute: MainAdminAuditLogsRoute,
  MainAdminIndexRoute: MainAdminIndexRoute,
}

const MainAdminRouteRouteWithChildren = MainAdminRouteRoute._addFileChildren(
  MainAdminRouteRouteChildren,
)

interface MainDocsRouteRouteChildren {
  MainDocsAiFeaturesRoute: typeof MainDocsAiFeaturesRoute
  MainDocsApplicationsRoute: typeof MainDocsApplicationsRoute
  MainDocsCandidatesRoute: typeof MainDocsCandidatesRoute
  MainDocsDocumentsRoute: typeof MainDocsDocumentsRoute
  MainDocsEmployeesRoute: typeof MainDocsEmployeesRoute
  MainDocsInterviewsRoute: typeof MainDocsInterviewsRoute
  MainDocsPositionsRoute: typeof MainDocsPositionsRoute
  MainDocsQuestionsRoute: typeof MainDocsQuestionsRoute
  MainDocsRoundsRoute: typeof MainDocsRoundsRoute
  MainDocsWhatsNewRoute: typeof MainDocsWhatsNewRoute
  MainDocsIndexRoute: typeof MainDocsIndexRoute
}

const MainDocsRouteRouteChildren: MainDocsRouteRouteChildren = {
  MainDocsAiFeaturesRoute: MainDocsAiFeaturesRoute,
  MainDocsApplicationsRoute: MainDocsApplicationsRoute,
  MainDocsCandidatesRoute: MainDocsCandidatesRoute,
  MainDocsDocumentsRoute: MainDocsDocumentsRoute,
  MainDocsEmployeesRoute: MainDocsEmployeesRoute,
  MainDocsInterviewsRoute: MainDocsInterviewsRoute,
  MainDocsPositionsRoute: MainDocsPositionsRoute,
  MainDocsQuestionsRoute: MainDocsQuestionsRoute,
  MainDocsRoundsRoute: MainDocsRoundsRoute,
  MainDocsWhatsNewRoute: MainDocsWhatsNewRoute,
  MainDocsIndexRoute: MainDocsIndexRoute,
}

const MainDocsRouteRouteWithChildren = MainDocsRouteRoute._addFileChildren(
  MainDocsRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAdminRouteRoute: typeof MainAdminRouteRouteWithChildren
  MainDocsRouteRoute: typeof MainDocsRouteRouteWithChildren
  MainDashboardRoute: typeof MainDashboardRoute
  MainIndexRoute: typeof MainIndexRoute
  MainCandidatesNewRoute: typeof MainCandidatesNewRoute
  MainDocumentsNewRoute: typeof MainDocumentsNewRoute
  MainEmployeesNewRoute: typeof MainEmployeesNewRoute
  MainPositionsNewRoute: typeof MainPositionsNewRoute
  MainProfileUserIdRoute: typeof MainProfileUserIdRoute
  MainQuestionsNewRoute: typeof MainQuestionsNewRoute
  MainRoundsNewRoute: typeof MainRoundsNewRoute
  MainWeeklyCheckinRecordsRoute: typeof MainWeeklyCheckinRecordsRoute
  MainApplicationsIndexRoute: typeof MainApplicationsIndexRoute
  MainCandidatesIndexRoute: typeof MainCandidatesIndexRoute
  MainDocumentsIndexRoute: typeof MainDocumentsIndexRoute
  MainEmployeesIndexRoute: typeof MainEmployeesIndexRoute
  MainInterviewsIndexRoute: typeof MainInterviewsIndexRoute
  MainPositionsIndexRoute: typeof MainPositionsIndexRoute
  MainProfileIndexRoute: typeof MainProfileIndexRoute
  MainQuestionsIndexRoute: typeof MainQuestionsIndexRoute
  MainRoundsIndexRoute: typeof MainRoundsIndexRoute
  MainWeeklyCheckinIndexRoute: typeof MainWeeklyCheckinIndexRoute
  MainCandidatesUidEditRoute: typeof MainCandidatesUidEditRoute
  MainEmployeesIdEditRoute: typeof MainEmployeesIdEditRoute
  MainPositionsSlugEditRoute: typeof MainPositionsSlugEditRoute
  MainQuestionsIdEditRoute: typeof MainQuestionsIdEditRoute
  MainRoundsIdAddQuestionRoute: typeof MainRoundsIdAddQuestionRoute
  MainRoundsIdEditRoute: typeof MainRoundsIdEditRoute
  MainApplicationsIdIndexRoute: typeof MainApplicationsIdIndexRoute
  MainCandidatesUidIndexRoute: typeof MainCandidatesUidIndexRoute
  MainEmployeesIdIndexRoute: typeof MainEmployeesIdIndexRoute
  MainInterviewsIdIndexRoute: typeof MainInterviewsIdIndexRoute
  MainPositionsSlugIndexRoute: typeof MainPositionsSlugIndexRoute
  MainQuestionsIdIndexRoute: typeof MainQuestionsIdIndexRoute
  MainRoundsIdIndexRoute: typeof MainRoundsIdIndexRoute
  MainCandidatesUidDocumentsDocumentIdEditRoute: typeof MainCandidatesUidDocumentsDocumentIdEditRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAdminRouteRoute: MainAdminRouteRouteWithChildren,
  MainDocsRouteRoute: MainDocsRouteRouteWithChildren,
  MainDashboardRoute: MainDashboardRoute,
  MainIndexRoute: MainIndexRoute,
  MainCandidatesNewRoute: MainCandidatesNewRoute,
  MainDocumentsNewRoute: MainDocumentsNewRoute,
  MainEmployeesNewRoute: MainEmployeesNewRoute,
  MainPositionsNewRoute: MainPositionsNewRoute,
  MainProfileUserIdRoute: MainProfileUserIdRoute,
  MainQuestionsNewRoute: MainQuestionsNewRoute,
  MainRoundsNewRoute: MainRoundsNewRoute,
  MainWeeklyCheckinRecordsRoute: MainWeeklyCheckinRecordsRoute,
  MainApplicationsIndexRoute: MainApplicationsIndexRoute,
  MainCandidatesIndexRoute: MainCandidatesIndexRoute,
  MainDocumentsIndexRoute: MainDocumentsIndexRoute,
  MainEmployeesIndexRoute: MainEmployeesIndexRoute,
  MainInterviewsIndexRoute: MainInterviewsIndexRoute,
  MainPositionsIndexRoute: MainPositionsIndexRoute,
  MainProfileIndexRoute: MainProfileIndexRoute,
  MainQuestionsIndexRoute: MainQuestionsIndexRoute,
  MainRoundsIndexRoute: MainRoundsIndexRoute,
  MainWeeklyCheckinIndexRoute: MainWeeklyCheckinIndexRoute,
  MainCandidatesUidEditRoute: MainCandidatesUidEditRoute,
  MainEmployeesIdEditRoute: MainEmployeesIdEditRoute,
  MainPositionsSlugEditRoute: MainPositionsSlugEditRoute,
  MainQuestionsIdEditRoute: MainQuestionsIdEditRoute,
  MainRoundsIdAddQuestionRoute: MainRoundsIdAddQuestionRoute,
  MainRoundsIdEditRoute: MainRoundsIdEditRoute,
  MainApplicationsIdIndexRoute: MainApplicationsIdIndexRoute,
  MainCandidatesUidIndexRoute: MainCandidatesUidIndexRoute,
  MainEmployeesIdIndexRoute: MainEmployeesIdIndexRoute,
  MainInterviewsIdIndexRoute: MainInterviewsIdIndexRoute,
  MainPositionsSlugIndexRoute: MainPositionsSlugIndexRoute,
  MainQuestionsIdIndexRoute: MainQuestionsIdIndexRoute,
  MainRoundsIdIndexRoute: MainRoundsIdIndexRoute,
  MainCandidatesUidDocumentsDocumentIdEditRoute:
    MainCandidatesUidDocumentsDocumentIdEditRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface ApiCandidateIdDocumentsRouteChildren {
  ApiCandidateIdDocumentsDocumentIdRoute: typeof ApiCandidateIdDocumentsDocumentIdRoute
}

const ApiCandidateIdDocumentsRouteChildren: ApiCandidateIdDocumentsRouteChildren =
  {
    ApiCandidateIdDocumentsDocumentIdRoute:
      ApiCandidateIdDocumentsDocumentIdRoute,
  }

const ApiCandidateIdDocumentsRouteWithChildren =
  ApiCandidateIdDocumentsRoute._addFileChildren(
    ApiCandidateIdDocumentsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInterviewSessionsRoute: ApiInterviewSessionsRoute,
  ApiAuditLogsGenerateReportRoute: ApiAuditLogsGenerateReportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCandidateBulkRoute: ApiCandidateBulkRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
  ApiDocumentsViewRoute: ApiDocumentsViewRoute,
  ApiLoginGoogleRoute: ApiLoginGoogleRoute,
  ApiCandidateIndexRoute: ApiCandidateIndexRoute,
  InterviewTokenIndexRoute: InterviewTokenIndexRoute,
  ApiCandidateIdAiAnalysisRoute: ApiCandidateIdAiAnalysisRoute,
  ApiCandidateIdAiScreeningRoute: ApiCandidateIdAiScreeningRoute,
  ApiCandidateIdDocumentsRoute: ApiCandidateIdDocumentsRouteWithChildren,
  ApiInterviewTokenTokenCompleteRoute: ApiInterviewTokenTokenCompleteRoute,
  ApiInterviewTokenTokenResponsesRoute: ApiInterviewTokenTokenResponsesRoute,
  ApiInterviewTokenTokenSchemaRoute: ApiInterviewTokenTokenSchemaRoute,
  ApiInterviewTokenTokenValidateRoute: ApiInterviewTokenTokenValidateRoute,
  ApiInterviewIdAiAnalysisRoute: ApiInterviewIdAiAnalysisRoute,
  ApiCandidateIdIndexRoute: ApiCandidateIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
